import streamlit as st



st.title("AP Cal AB Study Guide (Semester 1)")
st.header("1. Limits")
st.link_button("Openstax-chapter 2", "https://openstax.org/books/calculus-volume-1/pages/2-review-exercises")
st.link_button("AP Classroom-Unit 1", "https://apstudents.collegeboard.org/courses/ap-calculus-ab")
st.link_button("Khan Academy-Unit 1", "https://www.khanacademy.org/math/ap-calculus-ab/ab-limits-new")
st.subheader("Learning objectives")
st.write("a. Estimate Limits from graphs c. Determine Limits alegbraically")
st.write("b. Estimate limits from tables")
st.write("c. Determine Limits alegbraically")
st.write("d. Determining continuity")
st.write("Vertical + Horizontal asymptotes")
#math
st.subheader("Ex1")
st.latex(r'''lim_{x\to-3} \frac{x^2-9}{x^2-2x-15} =	''')
st.latex(r'''lim_{x\to-3} \frac{(x-3)(x+3)}{(x-5)(x+3)} = lim_{x\to-3} \frac{x-3}{x-5} =	''')
st.latex(r'''\frac{(-3)-3}{(-3)-5} = \frac{-6}{-8} = \frac{3}{4} ''')

st.header("L'Hopital's Rule")
st.write("if to crazy, use L'Hopitals Rule to find any 0/0 Limit")
st.caption("derivative of numerator + denomenator, then take the limit again.")

st.subheader("Ex1")
st.latex(r'''lim_{x\to-3} \frac{x^2-9}{2x-2x-15} = lim_{x\to-3} \frac{2x}{2x-2} = \frac{-6}{-8} = \frac{3}{4}''')

st.header("Continuity")
st.latex(r'''lim_{x\to a^-} f(x) = lim_{x\to a^+} f(x) = f(a)''')
st.subheader("types of discontinuity")
st.caption("Hole (removable)")
st.caption("Jump ")
st.caption("infinite (vertical asymptote)")

st.subheader("vertical Asymptotes")
st.latex(r'''lim_{x\to a} f(x) = \frac{num}{0}''')

st.subheader("Horizontal Asymptotes")
st.caption("if degrees are the same -> coefficients of highest terms")
st.caption("denomenator deg > numerator deg -> HA is y = 0")
st.caption("Numerator degree > Denomenator degree -> No HA (infinite)")
st.caption("heirarchy for HA exp > poly > log > sin/cos ")

st.divider()

st.header("Derivatives fundamentals")
st.link_button("Openstax-chapter 3", "https://openstax.org/books/calculus-volume-1/pages/3-review-exercises")
st.link_button("AP Classroom-Unit 2 + 3.1", "https://apstudents.collegeboard.org/courses/ap-calculus-ab")
st.link_button("Khan Academy-Unit 2 + 3.1", "https://www.khanacademy.org/math/ap-calculus-ab/ab-differentiation-1-new")

st.subheader("learning objectives")
st.write("a. definition of a derivative")
st.write("b. power, product, Quotient Rules")
st.write("c. chain Rule")
st.write("d. trig,log,exp")
st.write("e. Implicit Differentiation")
st.write("f. Differentiability implies continuity")

st.subheader("Rate of change = ")
st.latex(r'''\frac{\varDelta y}{\varDelta x} = \frac{y{2}-y{1}}{x{2}-x{1}} = \frac{rise}{run}''')
st.caption("the 2 and 1 in both x and y are supposed to be under it (I couldn't figure it out)")

st.subheader("Instaneous rate of change")
st.latex(r'''f'(x) = lim_{x\to c} \frac{f(c)-f(x)}{c-x}''')
st.caption("slope of tan line to f(x) at x=c")
st.caption("instantaneous rate of change of f(x) at x=c")
st.caption("derivative of f(x) at x=c")

st.write("Derivative at any point")
st.latex(r'''lim_{h\to 0} \frac{f(x+h)} {h} = f'(x)''')

st.subheader("Derivatives the easy way")
st.latex(r'''\frac{d}{dx} x^n = nx^{n-1}''')
st.latex(r'''\frac{d}{dx} K = 0''')
st.latex(r'''\frac{d}{dx} K * f(x) = K * f'(x)''')
st.latex(r'''\frac{d}{dx} e^x = e^x''')
st.latex(r'''\frac{d}{dx} ln(x) = \frac{1}{x}''')
st.latex(r'''\frac{d}{dx} sin(x) = cos(x)''')
st.latex(r'''\frac{d}{dx} cos(x) = -sin(x)''')
st.latex(r'''\frac{d}{dx} tax(x) = \frac{d}{dx} \frac{sin(x)}{cos(x)} = sec^2x''')
st.latex(r'''\frac{d}{dx} cot(x) = -csc^2x''')
st.latex(r'''\frac{d}{dx} sec(x) = sec(x) tan(x)''')
st.latex(r'''\frac{d}{dx} csc(x) = -csc(x) cot(x)''')
st.write("product rule")
st.latex(r''' y = f(x)*g(x), \frac{dy}{dx} = f'(x)g(x) + f(x)g'(x)''')
st.write("quotient rule")
st.latex(r'''y = \frac{f(x)}{g(x)}, \frac{dy}{dx} = \frac{f'(x)g(x)-f(x)g'(x)}{g(x)^2}''')
st.write("chain rule- for composite functions")
st.latex(r'''\frac{d}{dx} [f(g(x))] = f'(g(x))g'(x)''')
st.write("ex1")
st.latex(r'''y = (7x+5)^2''')
st.latex(r'''\frac{d}{dx} = 2(7x+5)*7''')
st.latex(r'''14(7x+5)''')

st.write("U-Sub")
st.caption("let u = 7x+5")
st.latex(r'''y = u^2''')
st.latex(r'''\frac{d}{dx} = 7''')
st.latex(r'''\frac{dy}{dx} = 2u''')
st.latex(r'''\frac{d}{dx} = \frac{dy}{du} * \frac{du}{dx} = 2u*7''')
st.latex(r'''14(7x+5)''')

st.write("Implicit Differentiation")
st.caption("multiply any y' by dy/dx")
st.write("ex1")
st.latex(r'''5y^2 + 3 = 8x^4''')
st.latex(r'''10y \frac{d}{dx} = 32x^3''')
st.latex(r'''\frac{d}{dx} = \frac{32x^3}{10y}''')

st.write("higher order derivatives")
st.latex(r'''f'(x) = \frac{d}{dx} = x^5''')
st.latex(r'''f''(x) \frac{d^2y}{dx^3} = f'(x) = 5x, f''(x) = 20''')
st.latex(r'''f'(x) = \frac{d^3}{dx^3} = f''(x) = 60x''')
st.caption("the last one is f triple prime")

st.subheader("differentiable means continuous")
st.caption("a function is not differentiable a^1 a print if")
st.caption("1. slope abruptly changest at that point ")
st.caption("2. Not continuous (vertical asymptote)")
st.caption("3. vertical tangent line(m=infinite, m = 1/0")
st.write(" when asked for equations of tangent line, use point slope form ")
st.latex(r'''m= f'(x,)''')
st.caption("slope")
st.latex(r'''(x,f(x,))''')
st.caption("point")
st.latex(r''' y = y_{1} = m(x-x_{1})''')

st.divider()


st.header("Derivative Applications")
st.link_button("Openstax-chapter 4", "https://openstax.org/books/calculus-volume-1/pages/4-introduction")
st.link_button("AP Classroom-Unit 4+5", "https://apstudents.collegeboard.org/courses/ap-calculus-ab")
st.link_button("Khan Academy-Unit 4", "https://www.khanacademy.org/math/ap-calculus-ab/ab-diff-contextual-applications-new")
st.link_button("Khan Academy-Unit 5", "https://www.khanacademy.org/math/ap-calculus-ab/ab-diff-analytical-applications-new")

st.subheader("learning objectives")
st.write("a. related rates")
st.write("b. position, velocity, Acceleration")
st.write("c. curve sketching/ graph analysis - f'(x), f''(x)")

st.subheader("Related Rates")
st.write("GWKA- Given, want, know, analysis")
st.write("1. diagram")
st.write("2. assign variables or derivatives")
st.write("3. list all given and unknown")
st.write("4. write an equation")
st.write("5. use chain rule, differentiate w/ respect to time")
st.write("6. substitute and solve for required rate of change")

st.write("position = x(t)")
st.write("velocity = v(t) = x'(t)")
st.write("acceleration = a(t) = v'(t) =x''(t)")

st. subheader("Relative extrema")
st.write(" local min/max = f' = 0 ")
st.latex(r'''max f' = t, f' = 0 f'= -''')
st.write(" vs. ")
st.latex(r'''min f' = -, f'= 0 f'=t''')
st.write("absolute extrema = highest max and lowest min")
st.write(" concavity")
st.latex(r'''up -> slope = f', is ,increasing, f'', is, positive \bigcup''')
st.latex(r'''down -> slope = f', is ,decreasing, f'', is, negative \bigcap''')

st.subheader("inflection point")
st.write("1. f(x) changes concavity")
st.write("2. f'(x) changes inc/dec or dec/inc relative extrema of f'")
st.write("3. f''(x) changes sign.... crosses x-axis")

st.caption("made by Avie Saini")
